# Quantumult X - rewrite_remote
# 只保留 rewrite 规则，避免导入报“格式不对”

[rewrite_local]
^http://cfui\.com(/.*)?$ url script-response-body https://raw.githubusercontent.com/2473-t/javaScript/main/cf-optimizer-ui.js
^https://cfui\.com(/.*)?$ url script-response-body https://raw.githubusercontent.com/2473-t/javaScript/main/cf-optimizer-ui.js
