# Quantumult X - task_remote
# 任务请作为 task_remote 单独导入

[task_local]
13 */4 * * * https://raw.githubusercontent.com/2473-t/javaScript/main/cf-ip-optimizer.js#auto, tag=CF优选, enabled=true
0 9 * * * https://raw.githubusercontent.com/2473-t/javaScript/main/cf-node-gen.js#auto, tag=CF生成节点, enabled=true
